Rails:
  Enabled: true

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

