# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3bfbd2f5cc1d8fe0f88e05b0485130a60c22b2a53b91d696ebd6007e5bac8a20f5a4678398dd80a2e71ab1c318a0334fb6b24d42e63d7e6e3581176f6ae80b34

test:
  secret_key_base: 1ea9b3456cb9373998caf1f44ae92467a46de12da49e283ce92171a2010310dec3044d00f69c5fcd6bea9859e921ec8b50d4fb85ead7c47f73313cd06b51db4e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
